### ISSUE TITLE
`release <version>`

### ISSUE THREAD

**Issue by ewen-lbh** [aogier/chachacha#24]
Add an optional `<version>` argument to `chachacha release` so that we can upgrade to arbitrary versions. I'm planning on using chachacha in my release script but I invoke this script `./release.py <version>` and would rather not have to convert from absolute to relative (i.e. major/minor/patch bumps)

**Comment by milliams** [comment]
I agree that this would be very useful. I'm using Poetry to manage my version and I'd like to be able to do:
```bash
poetry version minor
new_version=$(poetry version | awk '{print $2}')
chachacha release "${new_version}"
```

I can put a PR together if that would be useful?

**Comment by aogier** [comment]
Dear @ewen-lbh , @milliams , thank you for your interest in this humble project and please forgive me for my latency, had some problems. Anyway, that feature suggestion seems totally sensible to me and I'll be glad to include it asap, give me a bit of time because in my timezone is still work time, I'll ping you asap in some hours!

**Comment by aogier** [comment]
Hello! I've just merged your patch, thank you for the good work! Release machinery has just completed publishing jobs, thank you all and have a nice day!
